<?php
	$categories = $this->getCategoryCollection();
	$canShowImg = $this->canShowImage();
?>
<div class="mpamp-categories">
<?php foreach($categories as $category):?>
    <div class="mpamp-category" style="background: url('<?php echo $block->escapeUrl($category->getImageUrl()) ?>')">
        <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
            <h2 class="mpamp-category-title"><?php echo $block->escapeHtml($category->getName()) ?></h2>
        </a>
    </div>
<?php
endforeach;
?>
</div>