<?php
	$categories = $this->getCategoryCollection();
	$canShowImg = $this->canShowImage();
?>
<div class="mpamp-categories">
<?php (count($categories) % 2 != 0) ? $lastOddClass = "last-odd" : $lastOddClass = "" ?>
    <?php $categoriesCount = count($categories) ?>
<?php $counter = 0 ?>
<?php foreach($categories as $category):?>
    <div class="mpamp-category <?php if ($counter == $categoriesCount - 1) echo $lastOddClass ?>" style="background: url('<?php echo $block->escapeUrl($category->getImageUrl()) ?>')">
        <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
            <h2 class="mpamp-category-title"><?php echo $block->escapeHtml($category->getName()) ?></h2>
            <?php $counter++ ?>
        </a>
    </div>
<?php
endforeach;
?>
</div>